# Generated by Django 5.2 on 2025-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0002_alter_defeito_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defeito',
            options={'ordering': ['criado_em']},
        ),
        migrations.AlterField(
            model_name='defeito',
            name='maquina',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='defeito',
            table='Defeito',
        ),
    ]
