# Generated by Django 5.2 on 2025-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0003_alter_defeito_options_alter_defeito_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defeito',
            name='solucao',
            field=models.TextField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
