# Generated by Django 5.2 on 2025-04-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0004_defeito_solucao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defeito',
            options={},
        ),
    ]
