# Generated by Django 5.2 on 2025-04-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_conhecimento', '0005_alter_defeito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='defeito',
            name='causa_possivel',
            field=models.TextField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
